---
title: "p8105_hw5_hm2946.Rmd"
author: "min"
date: "2022-11-13"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 1

*read the data*
```{r}
p1_data = 
  tibble(
    files = list.files("data/problem1/"),
    path = str_c("data/problem1/", files)
  ) %>% 
  mutate(data = map(path, read_csv)) %>% 
  unnest(cols = c(data))
```

*Clean the data*
```{r}
p1_tidy = 
  p1_data %>% 
  mutate(
    files = str_replace(files, ".csv", ""),
    group = str_sub(files, 1, 3)) %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "outcome",
    names_prefix = "week_") %>% 
  mutate(week = as.numeric(week)) %>% 
  select(group, subj = files, week, outcome)
```

*plot*
```{r}
p1_tidy %>% 
  ggplot(aes(x = week, y = outcome, group = subj, color = group)) + 
  geom_point() + 
  geom_path() + 
  facet_grid(~group)
```

In the control arm: the outcome doesn't change much as time passes
In the experiment arm: the outcome increases linearly as time passes

